title: Stellarsonic
description: A record blog
url: https://stellarsonic.netlify.app
pages:
  - path: mixtapes
    title: Mixtapes
    type: blog
    #collection: mixes
    limit: 4
    pagination: true
    posts:
      path: mixtapes/{slug}
      type: playlist
      collection: mixes
