title: Stellarsonic
description: A record blog
url: https://stellarsonic.netlify.app
pages:
  - path: mixtapes
    title: Mixtapes
    type: gallery
    collection: mixes
    limit: 4
    pagination: true
